### ISSUE TITLE
psl command-line tool NULL pointer dereference

### ISSUE THREAD

**Issue by mschiffm** [rockdaboot/libpsl#106]
The psl tool when used with the `--print-reg-domain` flag does not check the return value of `psl_registrable_domain()` which returns `NULL` if the input does not contain a private suffix or if the psl context is `NULL`. When this happens the tool dereferences that NULL pointer and segfaults:

```
$gdb --args psl --print-reg-domain gov.ac
Segmentation fault
(gdb) run
Starting program: /usr/local/bin/psl --print-reg-domain gov.ac

Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106     ../sysdeps/x86_64/strlen.S: No such file or directory.
(gdb) bt
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007ffff732ef72 in _IO_puts (str=0x0) at ioputs.c:35
#2  0x0000555555555867 in main (argc=<optimized out>, argv=<optimized out>) at psl.c:246
(gdb) fr 2
#2  0x0000555555555867 in main (argc=<optimized out>, argv=<optimized out>) at psl.c:246
246                             printf("%s\n", psl_registrable_domain(psl, *arg));
(gdb) list
241             }
242             else if (mode == 3) {
243                     for (; arg < argv + argc; arg++) {
244                             if (!batch_mode)
245                                     printf("%s: ", *arg);
246                             printf("%s\n", psl_registrable_domain(psl, *arg));
247                     }
248             }
249             else if (mode == 4) {
250                     for (; arg < argv + argc; arg++) {
```
The fix is to simply check the return value of `psl_unregistrable_domain()` on line 246 and handling the aforementioned corner cases before referencing its result.

Note the same flow exists for the `--print-reg-domain` flag and `psl_unregistrable_domain()` function call in tools/psl.c:239.

**Comment by rockdaboot** [comment]
Fixed and pushed. Thanks for reporting. (Still interested in the OS/libc versions).

**Comment by mschiffm** [comment]
Sure, below:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.3 (stretch)
Release:        9.3
Codename:       stretch
$ /lib/x86_64-linux-gnu/libc.so.6
GNU C Library (Debian GLIBC 2.24-11+deb9u1) stable release version 2.24, by Roland McGrath et al.
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 6.3.0 20170516.
Available extensions:
        crypt add-on version 2.1 by Michael Glad and others
        GNU Libidn by Simon Josefsson
        Native POSIX Threads Library by Ulrich Drepper et al
        BIND-8.2.3-T5B
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<http://www.debian.org/Bugs/>.
```
