### ISSUE TITLE
Unable to build latest on MacOS

### ISSUE THREAD

**Issue by xrd** [rockdaboot/libpsl#215]
I tried to build from source using both meson and autoconf but am blocked. 

Using autoconf, I ran `autoconf.sh` but do not see any configure script generated.

Using meson I see the following:

(I also tried using the `libpsl-0.21.0` branch, and with this got an issue when it couldn't find the `python` binary: does libpsl require python2.x? I'm using python 3.11 and don't have another installed so `python` is not in the path.)

```
 % meson builddir
The Meson build system
Version: 1.2.1
Source dir: /Users/xxx/Projects/Xxx/source/libpsl
Build dir: /Users/xxx/Projects/Xxx/source/libpsl/builddir
Build type: native build
Project name: libpsl
Project version: 0.21.2
C compiler for the host machine: cc (clang 14.0.0 "Apple clang version 14.0.0 (clang-1400.0.29.202)")
C linker for the host machine: cc ld64 820.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/local/bin/pkg-config (0.29.2)
Run-time dependency libidn2 found: YES 2.3.4
Library unistring found: YES
Run-time dependency iconv found: YES
Check usable header "unistd.h" : YES 
Check usable header "stdint.h" : YES 
Check usable header "alloca.h" : YES 
Check usable header "dirent.h" : YES 
Checking for function "alloca" : YES 
Checking for function "strndup" : YES 
Checking for function "clock_gettime" : YES 
Checking for function "fmemopen" : YES 
Checking for function "nl_langinfo" : YES 
Compiler for C supports function attribute visibility: YES 
Configuring config.h using configuration
Program python3 found: YES (/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11)
Configuring libpsl.h using configuration
Build targets in project: 13

Found ninja-1.11.1.git.kitware.jobserver-1 at /Library/Frameworks/Python.framework/Versions/Current/bin/ninja
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
xxx@xxxs-iMac libpsl % ninja -C builddir 
ninja: Entering directory `builddir'
[1/28] Generating src/suffixes_dafsa.h with a custom command
FAILED: src/suffixes_dafsa.h 
/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11 ../src/psl-make-dafsa --output-format=cxx+ /Users/xxx/Projects/Xxx/source/libpsl/list/public_suffix_list.dat src/suffixes_dafsa.h
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/encodings/idna.py", line 179, in encode
    result.extend(ToASCII(label))
                  ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/encodings/idna.py", line 71, in ToASCII
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xxx/Projects/Xxx/source/libpsl/builddir/../src/psl-make-dafsa", line 692, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/xxx/Projects/Xxx/source/libpsl/builddir/../src/psl-make-dafsa", line 686, in main
    outfile.write(converter(parser(infile, utf_mode, codecs), utf_mode, codecs))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Projects/Xxx/source/libpsl/builddir/../src/psl-make-dafsa", line 591, in parse_psl
    punycode = line.decode('utf-8').encode('idna')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
[2/28] Generating tests/psl.dafsa with a custom command
FAILED: tests/psl.dafsa 
/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11 ../src/psl-make-dafsa --output-format=binary /Users/xxx/Projects/Xxx/source/libpsl/list/public_suffix_list.dat tests/psl.dafsa
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/encodings/idna.py", line 179, in encode
    result.extend(ToASCII(label))
                  ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/encodings/idna.py", line 71, in ToASCII
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xxx/Projects/Xxx/source/libpsl/builddir/../src/psl-make-dafsa", line 692, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/xxx/Projects/Xxx/source/libpsl/builddir/../src/psl-make-dafsa", line 686, in main
    outfile.write(converter(parser(infile, utf_mode, codecs), utf_mode, codecs))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Projects/Xxx/source/libpsl/builddir/../src/psl-make-dafsa", line 591, in parse_psl
    punycode = line.decode('utf-8').encode('idna')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
[3/28] Generating tests/psl_ascii.dafsa with a custom command
FAILED: tests/psl_ascii.dafsa 
/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11 ../src/psl-make-dafsa --output-format=binary --encoding=ascii /Users/xxx/Projects/Xxx/source/libpsl/list/public_suffix_list.dat tests/psl_ascii.dafsa
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/encodings/idna.py", line 179, in encode
    result.extend(ToASCII(label))
                  ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/encodings/idna.py", line 71, in ToASCII
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xxx/Projects/Xxx/source/libpsl/builddir/../src/psl-make-dafsa", line 692, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/xxx/Projects/Xxx/source/libpsl/builddir/../src/psl-make-dafsa", line 686, in main
    outfile.write(converter(parser(infile, utf_mode, codecs), utf_mode, codecs))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Projects/Xxx/source/libpsl/builddir/../src/psl-make-dafsa", line 591, in parse_psl
    punycode = line.decode('utf-8').encode('idna')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
[6/28] Compiling C object tools/psl.p/psl.c.o
ninja: build stopped: subcommand failed.

```

**Comment by xrd** [comment]
FWIW, downloading the tarball does work and that got me a compiled version.

**Comment by rockdaboot** [comment]
Glad you were successful 😃 
Building from tarball is the recommended way for non-developers.
