### ISSUE TITLE
psl-make-dafsa doesn't work in python 3

### ISSUE THREAD

**Issue by daurnimator** [rockdaboot/libpsl#67]
```
Traceback (most recent call last):
  File "../src/psl-make-dafsa", line 665, in <module>
    sys.exit(main())
  File "../src/psl-make-dafsa", line 659, in main
    outfile.write(converter(parser(infile, utf_mode), utf_mode))
  File "../src/psl-make-dafsa", line 507, in words_to_cxx
    return words_to_whatever(words, to_cxx, utf_mode)
  File "../src/psl-make-dafsa", line 499, in words_to_whatever
    dafsa = to_dafsa(words, utf_mode)
  File "../src/psl-make-dafsa", line 278, in to_dafsa
    return [to_nodes(word, 0) for word in words]
  File "../src/psl-make-dafsa", line 278, in <listcomp>
    return [to_nodes(word, 0) for word in words]
  File "../src/psl-make-dafsa", line 267, in to_nodes
    return word[0], [to_nodes(word[1:], 0)]
  File "../src/psl-make-dafsa", line 267, in to_nodes
    return word[0], [to_nodes(word[1:], 0)]
  File "../src/psl-make-dafsa", line 267, in to_nodes
    return word[0], [to_nodes(word[1:], 0)]
  File "../src/psl-make-dafsa", line 276, in to_nodes
    raise InputError('Domain names must be printable ASCII or UTF-8')
__main__.InputError: Domain names must be printable ASCII or UTF-8
Failed to execute ../src/psl-make-dafsa
```

**Comment by daurnimator** [comment]
The `utf_mode` argument to `parse_psl2c` is unused. I guess that is where this issue will be addressed?

**Comment by rockdaboot** [comment]
I spent some time on changing the code to work on python2 and python3 without success resp. without having ugly constructs for checking the python version.

@liljenzin What does the python expert (you) say ? Is it a big deal or could you 'easily' do it ?

**Comment by liljenzin** [comment]
I will have a look, maybe not today but in a day or two. It should of course work with python3 as well.

**Comment by liljenzin** [comment]
I have created a pull request with a fix for python3 compatibility.

**Comment by rockdaboot** [comment]
Many thanks, passes all tests. python2  (2.7.12) python3 (3.5.2) create exactly the same binaries here.
